# fly.toml app configuration file generated for gabriel-portfolio on 2024-04-22T21:32:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gabriel-portfolio"
primary_region = "waw"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"